###

Get http://localhost:3000/pizza

###

Get http://localhost:3000/pizza/6451603364cb272dc3ff5819

###
POST http://localhost:3000/pizza
Content-Type: application/json

{
  "name": "Team Pizza",
  "description": "Not your pizza!",
  "toppings": [{"topping":"Grit"},{"topping":"Willpower"},{"topping":"Determination"}]
  }

###
PATCH http://localhost:3000/pizza/6451603364cb272dc3ff5819
Content-Type: application/json

{
  "name":"MODIFIED: Cheese and Pepperoni"
}

###
DELETE http://localhost:3000/pizza/6451603364cb272dc3ff5819
Content-Type: application/json


###

Get http://localhost:3000/pizzeria

###
POST http://localhost:3000/pizzeria
Content-Type: application/json

{
  "name": "Newest the corner Pizzeria",
  "phone": "111-222-3333"
}

###
Get http://localhost:3000/pizzeria/645165481a138f1a3c860b12

###
PATCH http://localhost:3000/pizzeria/644c4711c028dea88c368e5c
Content-Type: application/json

{
  "name": "Best Damn Team Pizzeria"
}

###
PATCH http://localhost:3000/pizzeria/userrating/645165481a138f1a3c860b12

{
  "userRating":"5.0"
}

###
DELETE http://localhost:3000/pizzeria/645043d7cf9800545387b424
Content-Type: application/json

