###

Get http://localhost:3000/pizza

###

Get http://localhost:3000/pizza/644b008c37378817cd1d0d95

###
POST http://localhost:3000/pizza
Content-Type: application/json

{
  "name": "Lazy Pizza",
  "description": "Not your pizza!",
  "toppings": [{"topping":"onion"},{"topping":"sausage"},{"topping":"gouda-cheese"}]
  }

###
PATCH http://localhost:3000/pizza/64504387cf9800545387b40f
Content-Type: application/json

{
  "name":"MODIFIED: Cheese and Pepperoni"
}

###
DELETE http://localhost:3000/pizza/64504387cf9800545387b40f
Content-Type: application/json

###

Get http://localhost:3000/pizzeria


###

Get http://localhost:3000/pizzeria/645049c0ec30581ab4c284c1


###
POST http://localhost:3000/pizzeria
Content-Type: application/json

{
  "name": "AROUND the corner Pizzeria",
  "phone": "111-222-1111"
}

###
DELETE http://localhost:3000/pizzeria/645043d7cf9800545387b424
Content-Type: application/json


###
PATCH http://localhost:3000/pizzeria/645049c0ec30581ab4c284c1
Content-Type: application/json

{
  "name": "Just another pizza shop"
}

###
PATCH http://localhost:3000/pizzeria/645043d7cf9800545387b424/4.9
Content-Type: application/json

{
  "userRating":"4.9"
}
