###

Get http://localhost:3000/pizza

###

Get http://localhost:3000/pizza/644b008c37378817cd1d0d95

###
POST http://localhost:3000/pizza
Content-Type: application/json

{
    "name": "The Newest Combination",
  "description": "New pizza!"
  }

###
PATCH http://localhost:3000/pizza/644b0d6b0efb0680513356c1
Content-Type: application/json

{
  "name":"MODIFIED: Cheese and Pepperoni"
}

###
DELETE http://localhost:3000/pizza/644c321497699f8506919a5c
Content-Type: application/json

###

Get http://localhost:3000/pizzeria


###

Get http://localhost:3000/pizzeria/644c3b19d18fedf164d1224c


###
POST http://localhost:3000/pizzeria
Content-Type: application/json

{
  "name": "hmmm",
  "phone": "111-111-1111"
}

###
DELETE http://localhost:3000/pizzeria/644c49b20ff8df0c6039754c
Content-Type: application/json


###
PATCH http://localhost:3000/pizza/644c3c607b9e154c281b2dbc/5
Content-Type: application/json

{
  "rating": 4
}
